#!/bin/bash
echo "================================================================================"
echo "PIPELINE VERIFICATION"
echo "================================================================================"
echo ""

echo "✓ Checking main files..."
echo ""

echo "1. stream_all.py:"
[ -f publishers/stream_all.py ] && echo "   ✓ EXISTS" || echo "   ✗ MISSING"
head -5 publishers/stream_all.py | grep -q "Stream All Tables" && echo "   ✓ CORRECT VERSION" || echo "   ✗ WRONG VERSION"
echo ""

echo "2. data_fetch.py:"
[ -f data_fetch.py ] && echo "   ✓ EXISTS" || echo "   ✗ MISSING"
head -10 data_fetch.py | grep -q "NATS-Based" && echo "   ✓ NATS VERSION (CORRECT)" || echo "   ✗ OLD PATHWAY VERSION"
echo ""

echo "3. print_features.py:"
[ -f print_features.py ] && echo "   ✓ EXISTS" || echo "   ✗ MISSING"
grep -q "NATS" print_features.py && echo "   ✓ USES NATS (CORRECT)" || echo "   ✗ WRONG VERSION"
echo ""

echo "================================================================================"
echo "NATS SERVER STATUS"
echo "================================================================================"
docker ps | grep nats-server && echo "✓ NATS server is running" || echo "✗ NATS server not running"
echo ""

echo "================================================================================"
echo "DOCUMENTATION"
echo "================================================================================"
[ -f PIPELINE_GUIDE.md ] && echo "✓ PIPELINE_GUIDE.md" || echo "✗ Missing"
[ -f SUMMARY.md ] && echo "✓ SUMMARY.md" || echo "✗ Missing"
echo ""

echo "================================================================================"
echo "READY TO RUN!"
echo "================================================================================"
echo ""
echo "Start the pipeline in 3 terminals:"
echo ""
echo "  Terminal 1: python data_fetch.py"
echo "  Terminal 2: python print_features.py"
echo "  Terminal 3: python publishers/stream_all.py"
echo ""
echo "For more details, see PIPELINE_GUIDE.md"
echo ""
