"""
Prometheus Metrics Integration for Transaction Pipeline + MLOps
Provides metrics collection and HTTP server for Prometheus scraping
"""
import time
from prometheus_client import (
    Counter, Histogram, Gauge, Summary,
    CollectorRegistry, start_http_server, generate_latest
)
from contextlib import contextmanager
import threading

# Global registry for metrics
_registry = CollectorRegistry()
_metrics_manager = None
_http_server_started = False
_server_lock = threading.Lock()

# ============================================================================
# METRIC DEFINITIONS
# ============================================================================

# ───────────────────────────────────────────────
# PUBLISHER METRICS (Stage: Data Injection)
# ───────────────────────────────────────────────

# Record processing rate across all stages
record_processing_rate = Counter(
    'pipeline_record_processing_total',
    'Total records processed by stage',
    ['stage'],  # stage = publisher, enrichment, dispatcher
    registry=_registry
)

# Publisher-specific: CSV injection rate
csv_rows_injected = Counter(
    'publisher_csv_rows_injected_total',
    'Total CSV rows written to temp stream file',
    registry=_registry
)

# NATS publish operations
nats_messages_published = Counter(
    'publisher_nats_messages_published_total',
    'Total messages published to NATS',
    ['topic'],
    registry=_registry
)

nats_publish_errors = Counter(
    'publisher_nats_publish_errors_total',
    'Total NATS publish errors',
    ['topic', 'error_type'],
    registry=_registry
)

# Current TPS gauge (for real-time monitoring)
current_tps = Gauge(
    'publisher_current_tps',
    'Current transactions per second being published',
    registry=_registry
)

# IO wait time for file operations
io_wait_duration = Histogram(
    'publisher_io_wait_duration_seconds',
    'Time spent waiting for file operations',
    ['operation'],  # operation = read, write, append
    buckets=[0.0001, 0.0005, 0.001, 0.005, 0.01, 0.05, 0.1, 0.5, 1.0],
    registry=_registry
)

# Buffer lag (difference between write position and read position)
buffer_lag_seconds = Gauge(
    'publisher_buffer_lag_seconds',
    'Time lag between CSV writer and Pathway reader',
    registry=_registry
)

# ───────────────────────────────────────────────
# ENRICHMENT METRICS (Stage: Customer 360)
# ───────────────────────────────────────────────

# Match rate tracking
master_match_success = Counter(
    'enrichment_master_match_success_total',
    'Transactions successfully joined with Customer ID',
    registry=_registry
)

master_match_fail = Counter(
    'enrichment_master_match_fail_total',
    'Transactions with unknown Customer ID (orphaned)',
    registry=_registry
)

# Financial aggregates
total_volume_processed = Counter(
    'enrichment_total_volume_processed',
    'Sum of transaction amounts processed (in currency units)',
    registry=_registry
)

average_credit_score = Gauge(
    'enrichment_average_credit_score',
    'Rolling average of final credit scores',
    registry=_registry
)

# Logic trigger counters
bounced_event_count = Counter(
    'enrichment_bounced_events_total',
    'Count of transactions with bounced_flag=True',
    ['component'],
    registry=_registry
)

high_value_event_count = Counter(
    'enrichment_high_value_events_total',
    'Count of high-value transactions',
    ['threshold_type'],  # e.g., 'above_50k', 'above_100k'
    registry=_registry
)

# Enrichment processing duration
enrichment_processing_duration = Histogram(
    'enrichment_processing_duration_seconds',
    'Time taken to enrich a record',
    buckets=[0.001, 0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1.0],
    registry=_registry
)

# ───────────────────────────────────────────────
# DISPATCHER METRICS (Stage: Lead Generation)
# ───────────────────────────────────────────────

# Lead generation by type
leads_generated = Counter(
    'dispatcher_leads_generated_total',
    'Total leads generated by type',
    ['type'],  # type = home, car, nifty, elss
    registry=_registry
)

# Rejection reasons
lead_rejections = Counter(
    'dispatcher_lead_rejections_total',
    'Leads rejected with reason',
    ['reason'],  # reason = cooldown, low_volume, already_opted, not_qualified
    registry=_registry
)

# Lead latency (time from transaction to lead generation)
lead_latency = Histogram(
    'dispatcher_lead_latency_seconds',
    'Time between transaction update and lead generation',
    buckets=[0.1, 0.5, 1.0, 5.0, 10.0, 30.0, 60.0, 300.0],
    registry=_registry
)

# Cooldown filter hits
cooldown_filter_hits = Counter(
    'dispatcher_cooldown_filter_hits_total',
    'Number of times cooldown filter prevented lead generation',
    ['lead_type'],
    registry=_registry
)

# ───────────────────────────────────────────────
# END-TO-END PIPELINE METRICS
# ───────────────────────────────────────────────

# End-to-end latency (from txn_datetime to lead published)
pipeline_end_to_end_latency = Histogram(
    'pipeline_end_to_end_latency_seconds',
    'Total time from transaction datetime to final output',
    ['stage_output'],  # enrichment, dispatcher
    buckets=[0.1, 0.5, 1.0, 5.0, 10.0, 30.0, 60.0, 300.0, 600.0],
    registry=_registry
)

# ───────────────────────────────────────────────
# NATS INFRASTRUCTURE METRICS
# ───────────────────────────────────────────────

# NATS queue depth
nats_queue_depth = Gauge(
    'nats_queue_depth',
    'Pending messages in NATS stream',
    ['stream'],  # stream = transactions.stream, updated.Customer
    registry=_registry
)

# NATS connection status
nats_connection_status = Gauge(
    'nats_connection_status',
    'NATS connection status (1=connected, 0=disconnected)',
    ['component'],
    registry=_registry
)

# ───────────────────────────────────────────────
# COMPONENT HEALTH METRICS
# ───────────────────────────────────────────────

component_uptime = Gauge(
    'pipeline_component_uptime_seconds',
    'Component uptime in seconds',
    ['component'],
    registry=_registry
)

component_errors = Counter(
    'pipeline_component_errors_total',
    'Total errors by component',
    ['component', 'error_type'],
    registry=_registry
)

# Memory usage tracking
component_memory_usage_bytes = Gauge(
    'pipeline_component_memory_usage_bytes',
    'Memory usage of component in bytes',
    ['component'],
    registry=_registry
)


# ============================================================================
# MLOPS METRICS (CAR LOAN PREDICTOR)
# ============================================================================

# ───────────────────────────────────────────────
# TRAINER METRICS (init_car_trainer.py)
# ───────────────────────────────────────────────

# Training sample count
ml_training_samples = Gauge(
    'ml_car_training_samples_total',
    'Number of positive samples used for training',
    registry=_registry
)

# Baseline model components
ml_baseline_components = Gauge(
    'ml_car_baseline_components',
    'Number of GMM components in baseline model',
    registry=_registry
)

# Training duration
ml_training_duration = Gauge(
    'ml_car_training_duration_seconds',
    'Time taken to train the baseline model',
    registry=_registry
)

# Feature dimension check
ml_feature_dimensions = Gauge(
    'ml_car_feature_dimensions',
    'Total number of features (numerical + categorical)',
    ['feature_type'],  # 'numerical' or 'categorical'
    registry=_registry
)

# Training status
ml_training_status = Gauge(
    'ml_car_training_status',
    'Training status (1=success, 0=failed)',
    registry=_registry
)

# ───────────────────────────────────────────────
# PREDICTOR METRICS (car_loan_prediction_node.py)
# ───────────────────────────────────────────────

# Prediction count by result
ml_predictions_total = Counter(
    'ml_car_predictions_total',
    'Total predictions made',
    ['result'],  # 'qualified' or 'rejected'
    registry=_registry
)

# Inference latency
ml_inference_latency = Histogram(
    'ml_car_inference_latency_seconds',
    'Time taken for GMM prediction (scaling + encoding + scoring)',
    buckets=[0.0001, 0.0005, 0.001, 0.005, 0.01, 0.025, 0.05, 0.1, 0.25],
    registry=_registry
)

# Confidence score distribution
ml_confidence_score = Histogram(
    'ml_car_confidence_score',
    'GMM confidence scores for predictions',
    buckets=[0.0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0],
    registry=_registry
)

# Average confidence score (for drift detection)
ml_avg_confidence_score = Gauge(
    'ml_car_avg_confidence_score',
    'Rolling average confidence score (for drift detection)',
    registry=_registry
)

# Cluster assignment distribution
ml_cluster_assignments = Counter(
    'ml_car_cluster_assignments_total',
    'Number of predictions assigned to each cluster',
    ['cluster_id'],
    registry=_registry
)

# Model reload counter
ml_model_reloads = Counter(
    'ml_car_model_reloads_total',
    'Number of times the model was reloaded from disk',
    registry=_registry
)

# Exemplar count per prediction
ml_exemplar_count = Histogram(
    'ml_car_exemplar_count',
    'Number of exemplars returned per prediction',
    buckets=[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    registry=_registry
)

# Prediction errors
ml_prediction_errors = Counter(
    'ml_car_prediction_errors_total',
    'Total prediction errors',
    ['error_type'],
    registry=_registry
)

# ───────────────────────────────────────────────
# FEEDBACK LOOP METRICS (car_loan_feedback_node.py)
# ───────────────────────────────────────────────

# Feedback volume
ml_feedback_received = Counter(
    'ml_car_feedback_received_total',
    'Total feedback points received',
    ['feedback_type'],  # 'positive' (bought) or 'negative' (not bought)
    registry=_registry
)

# Model complexity growth
ml_model_components = Gauge(
    'ml_car_model_components_current',
    'Current number of GMM components (tracks model complexity)',
    registry=_registry
)

# Update latency (model.update() + save time)
ml_update_latency = Histogram(
    'ml_car_update_latency_seconds',
    'Time taken to update model with feedback',
    buckets=[0.001, 0.005, 0.01, 0.05, 0.1, 0.5, 1.0, 5.0],
    registry=_registry
)

# Save latency (disk I/O)
ml_save_latency = Histogram(
    'ml_car_save_latency_seconds',
    'Time taken to save model to disk',
    buckets=[0.01, 0.05, 0.1, 0.5, 1.0, 2.0, 5.0],
    registry=_registry
)

# Save success/failure
ml_save_status = Counter(
    'ml_car_save_status_total',
    'Model save operations',
    ['status'],  # 'success' or 'failed'
    registry=_registry
)

# Feedback buffer size
ml_feedback_buffer_size = Gauge(
    'ml_car_feedback_buffer_size',
    'Current size of feedback buffer (pending updates)',
    registry=_registry
)

# Time since last save
ml_time_since_save = Gauge(
    'ml_car_time_since_last_save_seconds',
    'Seconds since last model save',
    registry=_registry
)

# Feedback processing errors
ml_feedback_errors = Counter(
    'ml_car_feedback_errors_total',
    'Feedback processing errors',
    ['error_type'],
    registry=_registry
)

# Batch update counter
ml_batch_updates = Counter(
    'ml_car_batch_updates_total',
    'Number of batch updates performed',
    registry=_registry
)


# ============================================================================
# PIPELINE OBSERVABILITY METRICS (Node-to-Node Latency, Qualifications, etc.)
# ============================================================================

# ───────────────────────────────────────────────
# 1. NODE-TO-NODE LATENCY (Inter-stage latency)
# ───────────────────────────────────────────────

# Latency between pipeline stages
node_to_node_latency = Histogram(
    'pipeline_node_to_node_latency_seconds',
    'Latency between pipeline nodes (from one stage to the next)',
    ['from_node', 'to_node'],  # e.g., publisher→enrichment, enrichment→dispatcher
    buckets=[0.001, 0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1.0, 2.5, 5.0, 10.0],
    registry=_registry
)

# Stage entry timestamps for latency calculation
stage_entry_timestamp = Gauge(
    'pipeline_stage_entry_timestamp',
    'Timestamp when record entered a stage (for latency calculation)',
    ['stage', 'record_id'],
    registry=_registry
)

# ───────────────────────────────────────────────
# 2. LEAD QUALIFICATION & CAR LOAN COUNTS
# ───────────────────────────────────────────────

# Lead qualification counter by product and stage
lead_qualification_total = Counter(
    'pipeline_lead_qualification_total',
    'Total leads qualified by product type and stage',
    ['product', 'stage'],  # product=car_loan/home_loan/nifty50/elss, stage=qualified/sent_to_call/ml_approved
    registry=_registry
)

# Car loan specific qualification funnel
car_loan_funnel = Counter(
    'pipeline_car_loan_funnel_total',
    'Car loan lead funnel stages',
    ['stage'],  # stage=volume_check/dispatched/ml_qualified/called
    registry=_registry
)

# Current qualified leads gauge (for real-time display)
current_qualified_leads = Gauge(
    'pipeline_current_qualified_leads',
    'Current count of qualified leads by product',
    ['product'],
    registry=_registry
)

# ───────────────────────────────────────────────
# 3. MODEL WEIGHT UPDATE COUNTER
# ───────────────────────────────────────────────

# Model weight updates counter
ml_model_weight_updates = Counter(
    'ml_model_weight_updates_total',
    'Total model weight updates from feedback loop',
    ['model_type', 'update_type'],  # model_type=car_loan, update_type=positive/negative
    registry=_registry
)

# Model weight update latency
ml_weight_update_latency = Histogram(
    'ml_model_weight_update_latency_seconds',
    'Time taken to update model weights',
    ['model_type'],
    buckets=[0.001, 0.005, 0.01, 0.05, 0.1, 0.5, 1.0, 5.0],
    registry=_registry
)

# ───────────────────────────────────────────────
# 4. CALL API CONVERSION TRACKING
# ───────────────────────────────────────────────

# Call API attempts (customers we tried to call)
call_api_attempts = Counter(
    'pipeline_call_api_attempts_total',
    'Total call API attempts (customers sent for calling)',
    ['product'],  # car_loan, home_loan, nifty50, elss
    registry=_registry
)

# Call API conversions (customers who actually bought)
call_api_conversions = Counter(
    'pipeline_call_api_conversions_total',
    'Conversions from call API (customer actually bought)',
    ['product'],
    registry=_registry
)

# Conversion rate gauge (for dashboard display)
call_conversion_rate = Gauge(
    'pipeline_call_conversion_rate',
    'Call-to-conversion rate (conversions/attempts)',
    ['product'],
    registry=_registry
)


# ============================================================================
# METRICS MANAGER CLASS
# ============================================================================

class MetricsManager:
    """Manages metrics collection and HTTP server"""
    
    def __init__(self, component_name: str, port: int = 8001):
        self.component_name = component_name
        self.port = port
        self.start_time = time.time()
        
    def start_http_server(self):
        """Start Prometheus HTTP server for metrics scraping"""
        global _http_server_started
        
        with _server_lock:
            if _http_server_started:
                print(f"   ℹ️  Metrics server already running on port {self.port}")
                return
            
            try:
                # Start HTTP server in separate thread
                start_http_server(self.port, registry=_registry)
                _http_server_started = True
                print(f"✅ Metrics server started on http://localhost:{self.port}/metrics")
                print(f"   Component: {self.component_name}")
            except OSError as e:
                if "Address already in use" in str(e):
                    print(f"⚠️  Port {self.port} already in use - metrics server not started")
                    print(f"   This is normal if multiple processes share the same port")
                else:
                    print(f"❌ Failed to start metrics server: {e}")
    
    def record_error(self, error_type: str):
        """Record an error"""
        component_errors.labels(
            component=self.component_name,
            error_type=error_type
        ).inc()
    
    def update_component_uptime(self):
        """Update component uptime metric"""
        uptime = time.time() - self.start_time
        component_uptime.labels(component=self.component_name).set(uptime)
    
    def get_metrics_text(self):
        """Get current metrics in Prometheus text format"""
        return generate_latest(_registry).decode('utf-8')


# ============================================================================
# CONVENIENCE FUNCTIONS
# ============================================================================

def initialize_metrics(component_name: str, port: int = 8001) -> MetricsManager:
    """
    Initialize metrics for a component and start HTTP server
    
    Args:
        component_name: Name of the component (publisher, enrichment, dispatcher)
        port: Port for Prometheus HTTP server
    
    Returns:
        MetricsManager instance
    """
    global _metrics_manager
    
    _metrics_manager = MetricsManager(component_name, port)
    _metrics_manager.start_http_server()
    
    # Initialize component uptime
    component_uptime.labels(component=component_name).set(0)
    
    # Initialize NATS connection status
    nats_connection_status.labels(component=component_name).set(0)
    
    return _metrics_manager


def get_metrics_manager() -> MetricsManager:
    """Get the global metrics manager instance"""
    return _metrics_manager


# ============================================================================
# PUBLISHER METRIC RECORDING FUNCTIONS
# ============================================================================

def record_csv_row_injected():
    """Record a CSV row written to temp stream file"""
    csv_rows_injected.inc()
    record_processing_rate.labels(stage="publisher").inc()


def record_nats_publish(topic: str, success: bool = True, error_type: str = None):
    """Record NATS message publish"""
    if success:
        nats_messages_published.labels(topic=topic).inc()
    else:
        nats_publish_errors.labels(topic=topic, error_type=error_type or "unknown").inc()


def update_current_tps(tps: float):
    """Update current TPS gauge"""
    current_tps.set(tps)


def record_io_wait(operation: str, duration: float):
    """Record IO wait time"""
    io_wait_duration.labels(operation=operation).observe(duration)


def update_buffer_lag(lag_seconds: float):
    """Update buffer lag gauge"""
    buffer_lag_seconds.set(lag_seconds)


# ============================================================================
# ENRICHMENT METRIC RECORDING FUNCTIONS
# ============================================================================

def record_master_match(success: bool):
    """Record customer master match result"""
    if success:
        master_match_success.inc()
    else:
        master_match_fail.inc()
    
    if success:
        record_processing_rate.labels(stage="enrichment").inc()


def record_transaction_volume(amount: float):
    """Record transaction amount processed"""
    total_volume_processed.inc(amount)


def update_average_credit_score(score: float):
    """Update rolling average credit score"""
    average_credit_score.set(score)


def record_bounced_event(component: str = "enrichment"):
    """Record a bounced transaction"""
    bounced_event_count.labels(component=component).inc()


def record_high_value_event(threshold_type: str):
    """Record a high-value transaction"""
    high_value_event_count.labels(threshold_type=threshold_type).inc()


def record_enrichment_duration(duration: float):
    """Record enrichment processing time"""
    enrichment_processing_duration.observe(duration)


# ============================================================================
# DISPATCHER METRIC RECORDING FUNCTIONS
# ============================================================================

def record_lead_generated(lead_type: str):
    """Record a lead generation"""
    leads_generated.labels(type=lead_type).inc()
    record_processing_rate.labels(stage="dispatcher").inc()


def record_lead_rejection(reason: str):
    """Record a lead rejection"""
    lead_rejections.labels(reason=reason).inc()


def record_lead_generation_latency(latency_seconds: float):
    """Record lead generation latency"""
    lead_latency.observe(latency_seconds)


def record_cooldown_hit(lead_type: str):
    """Record cooldown filter hit"""
    cooldown_filter_hits.labels(lead_type=lead_type).inc()


# ============================================================================
# PIPELINE METRIC RECORDING FUNCTIONS
# ============================================================================

def record_end_to_end_latency(stage_output: str, latency_seconds: float):
    """Record end-to-end pipeline latency"""
    pipeline_end_to_end_latency.labels(stage_output=stage_output).observe(latency_seconds)


def update_nats_queue_depth(stream: str, depth: int):
    """Update NATS queue depth"""
    nats_queue_depth.labels(stream=stream).set(depth)


def set_nats_connection_status(component: str, connected: bool):
    """Update NATS connection status"""
    nats_connection_status.labels(component=component).set(1 if connected else 0)


def update_memory_usage(component: str, bytes_used: int):
    """Update component memory usage"""
    component_memory_usage_bytes.labels(component=component).set(bytes_used)


# ============================================================================
# MLOPS METRIC RECORDING FUNCTIONS
# ============================================================================

# ───────────────────────────────────────────────
# TRAINER METRICS
# ───────────────────────────────────────────────

def record_training_samples(count: int):
    """Record number of training samples"""
    ml_training_samples.set(count)


def record_baseline_components(count: int):
    """Record baseline model components"""
    ml_baseline_components.set(count)


def record_training_duration(duration: float):
    """Record training duration"""
    ml_training_duration.set(duration)


def record_feature_dimensions(numerical: int, categorical: int):
    """Record feature dimensions"""
    ml_feature_dimensions.labels(feature_type='numerical').set(numerical)
    ml_feature_dimensions.labels(feature_type='categorical').set(categorical)


def record_training_status(success: bool):
    """Record training success/failure"""
    ml_training_status.set(1 if success else 0)


# ───────────────────────────────────────────────
# PREDICTOR METRICS
# ───────────────────────────────────────────────

def record_prediction(qualified: bool, cluster_id: int, confidence: float, exemplar_count: int):
    """Record a prediction with all metadata"""
    result = 'qualified' if qualified else 'rejected'
    ml_predictions_total.labels(result=result).inc()
    ml_confidence_score.observe(confidence)
    ml_cluster_assignments.labels(cluster_id=str(cluster_id)).inc()
    ml_exemplar_count.observe(exemplar_count)


def record_inference_time(duration: float):
    """Record inference latency"""
    ml_inference_latency.observe(duration)


def update_avg_confidence(score: float):
    """Update rolling average confidence score"""
    ml_avg_confidence_score.set(score)


def record_model_reload():
    """Record model reload event"""
    ml_model_reloads.inc()


def record_prediction_error(error_type: str):
    """Record prediction error"""
    ml_prediction_errors.labels(error_type=error_type).inc()


# ───────────────────────────────────────────────
# FEEDBACK LOOP METRICS
# ───────────────────────────────────────────────

def record_feedback(bought: bool):
    """Record feedback received"""
    feedback_type = 'positive' if bought else 'negative'
    ml_feedback_received.labels(feedback_type=feedback_type).inc()


def update_model_components(count: int):
    """Update current model component count"""
    ml_model_components.set(count)


def record_update_time(duration: float):
    """Record model update latency"""
    ml_update_latency.observe(duration)


def record_save_time(duration: float, success: bool):
    """Record model save operation"""
    ml_save_latency.observe(duration)
    status = 'success' if success else 'failed'
    ml_save_status.labels(status=status).inc()


def update_feedback_buffer_size(size: int):
    """Update feedback buffer size"""
    ml_feedback_buffer_size.set(size)


def update_time_since_save(seconds: float):
    """Update time since last save"""
    ml_time_since_save.set(seconds)


def record_feedback_error(error_type: str):
    """Record feedback processing error"""
    ml_feedback_errors.labels(error_type=error_type).inc()


def record_batch_update():
    """Record a batch update"""
    ml_batch_updates.inc()


# ============================================================================
# PIPELINE OBSERVABILITY RECORDING FUNCTIONS
# ============================================================================

# ───────────────────────────────────────────────
# NODE-TO-NODE LATENCY FUNCTIONS
# ───────────────────────────────────────────────

def record_node_to_node_latency(from_node: str, to_node: str, latency_seconds: float):
    """
    Record latency between two pipeline nodes
    
    Args:
        from_node: Source node (publisher, enrichment, dispatcher, predictor)
        to_node: Destination node
        latency_seconds: Time taken to move from one node to the next
    """
    node_to_node_latency.labels(from_node=from_node, to_node=to_node).observe(latency_seconds)


def record_stage_entry(stage: str, record_id: str, timestamp: float = None):
    """
    Record when a record enters a stage (for latency calculation)
    
    Args:
        stage: Stage name (publisher, enrichment, dispatcher, predictor, feedback)
        record_id: Unique identifier for the record (e.g., customer_id_timestamp)
        timestamp: Entry timestamp (defaults to current time)
    """
    if timestamp is None:
        timestamp = time.time()
    stage_entry_timestamp.labels(stage=stage, record_id=record_id).set(timestamp)


# ───────────────────────────────────────────────
# LEAD QUALIFICATION FUNCTIONS
# ───────────────────────────────────────────────

def record_lead_qualification(product: str, stage: str, count: int = 1):
    """
    Record lead qualification event
    
    Args:
        product: Product type (car_loan, home_loan, nifty50, elss)
        stage: Qualification stage (qualified, sent_to_call, ml_approved, converted)
        count: Number of leads (default 1)
    """
    lead_qualification_total.labels(product=product, stage=stage).inc(count)


def record_car_loan_funnel(stage: str, count: int = 1):
    """
    Record car loan funnel progression
    
    Args:
        stage: Funnel stage (volume_check, dispatched, ml_qualified, called, converted)
        count: Number of leads (default 1)
    """
    car_loan_funnel.labels(stage=stage).inc(count)


def update_qualified_leads_count(product: str, count: int):
    """
    Update current qualified leads gauge
    
    Args:
        product: Product type
        count: Current count of qualified leads
    """
    current_qualified_leads.labels(product=product).set(count)


# ───────────────────────────────────────────────
# MODEL WEIGHT UPDATE FUNCTIONS
# ───────────────────────────────────────────────

def record_model_weight_update(model_type: str, update_type: str, latency: float = None):
    """
    Record a model weight update
    
    Args:
        model_type: Type of model (car_loan, home_loan, etc.)
        update_type: Type of update (positive, negative)
        latency: Time taken for the update (optional)
    """
    ml_model_weight_updates.labels(model_type=model_type, update_type=update_type).inc()
    if latency is not None:
        ml_weight_update_latency.labels(model_type=model_type).observe(latency)


# ───────────────────────────────────────────────
# CALL API CONVERSION FUNCTIONS
# ───────────────────────────────────────────────

def record_call_api_attempt(product: str, count: int = 1):
    """
    Record a call API attempt (customer sent for calling)
    
    Args:
        product: Product type (car_loan, home_loan, nifty50, elss)
        count: Number of attempts (default 1)
    """
    call_api_attempts.labels(product=product).inc(count)


def record_call_api_conversion(product: str, count: int = 1):
    """
    Record a call API conversion (customer actually bought)
    
    Args:
        product: Product type
        count: Number of conversions (default 1)
    """
    call_api_conversions.labels(product=product).inc(count)


def update_call_conversion_rate(product: str, rate: float):
    """
    Update the call-to-conversion rate
    
    Args:
        product: Product type
        rate: Conversion rate (0.0 to 1.0)
    """
    call_conversion_rate.labels(product=product).set(rate)


# ============================================================================
# CONTEXT MANAGER FOR TIMING
# ============================================================================

@contextmanager
def MetricsTimer(metric_func, *args, **kwargs):
    """
    Context manager for timing operations
    
    Usage:
        with MetricsTimer(record_enrichment_duration):
            # ... code to time ...
    """
    start = time.time()
    try:
        yield
    finally:
        duration = time.time() - start
        metric_func(duration, *args, **kwargs)


# ============================================================================
# UTILITY FUNCTIONS
# ============================================================================

def get_current_metrics():
    """Get current metrics as text (for debugging)"""
    return generate_latest(_registry).decode('utf-8')


def reset_metrics():
    """Reset all metrics (for testing)"""
    global _registry, _metrics_manager, _http_server_started
    _registry = CollectorRegistry()
    _metrics_manager = None
    _http_server_started = False


# ============================================================================
# HEALTH CHECK
# ============================================================================

def metrics_health_check():
    """Check if metrics system is healthy"""
    try:
        metrics_text = get_current_metrics()
        return len(metrics_text) > 0
    except Exception as e:
        print(f"❌ Metrics health check failed: {e}")
        return False


if __name__ == "__main__":
    # Test metrics server
    print("Testing Prometheus metrics server...")
    manager = initialize_metrics("test_component", port=8001)
    
    # Record some test metrics
    record_csv_row_injected()
    record_nats_publish("test.topic", success=True)
    update_current_tps(20.5)
    record_master_match(success=True)
    record_lead_generated("home")
    
    # Test ML metrics
    record_training_samples(1000)
    record_prediction(qualified=True, cluster_id=2, confidence=0.85, exemplar_count=3)
    record_feedback(bought=True)
    
    print("\n📊 Current metrics (first 1000 chars):")
    print(get_current_metrics()[:1000])
    print("\n✅ Metrics server running. Press Ctrl+C to stop.")
    print(f"   Visit: http://localhost:8001/metrics")
    
    try:
        # Keep server running
        while True:
            time.sleep(1)
            manager.update_component_uptime()
    except KeyboardInterrupt:
        print("\n\n👋 Shutting down...")